# escape=`

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

ARG BASE_IMAGE
FROM ${BASE_IMAGE} as silversim
ARG LICENSE_SERVER

LABEL maintainer="Marin Stanev <stanev@synopsys.com>" `
      description="Docker image to run Silver and TestWeaver"

#Limit execution privilege
RUN net user /add appuser
USER appuser
WORKDIR /app

#Add SNPS License Server information
ENV SNPSLMD_LICENSE_FILE=${LICENSE_SERVER}

#Install Silver
COPY silver_installation_properties.inf /app/
COPY SilverSetup*.exe /app/SilverSetup.exe

RUN .\SilverSetup.exe /LOADINF="silver_installation_properties.inf" /VERYSILENT /FORCECLOSEAPPLICATIONS /SUPPRESSMSGBOXES /SP-

WORKDIR /app/build
ENTRYPOINT silversim.exe
#=======================================================================================================================================================
FROM silversim as sbsbuild

ENTRYPOINT sbsBuild.exe
